server:
  port: 8099
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    data-username: root
    data-password: 15760959449

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

